# Load Data

In [536]:
import glob
import os
#aaa
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import rasterio 
import pdb #for adding breakpoints to code
from sklearn.model_selection import train_test_split

# Load Dataset into Memory


In [537]:
#code r'C:\Users\Usselman Lab\VNA_model'


In [538]:
# Specify the path to the root directory
root_directory = r'E:\GitRepo\rawdata'  # Change this to the actual path
# Use glob to get paths of all text files in the subdirectories
text_file_paths = glob.glob(os.path.join(root_directory, '*', '*.txt'))

# Print the list of file paths
#for file_path in text_file_paths:
    #print(file_path)

# Creates an empty list to store the X data in
X = []

# Creates an empty list to store the Y data in (Y data is just all of the different 15 samples)
Y = []

for file_path in text_file_paths:
    X.append(pd.read_csv(file_path, sep = '\t', skiprows = 16).drop(columns = ['PNT','FREQ1.GHZ','FREQ2.GHZ', 'LOGMAG2', 'FREQ3.GHZ', 'FREQ4.GHZ','LOGMAG3', 'LOGMAG4']).to_numpy())
    # Grab the folder name as a label for each array
    folder_name = os.path.basename(os.path.dirname(file_path))
    Y.append(folder_name)
print(X)
print ((hex(id(Y))))
print (id(Y))
print(len(Y))




[array([[-48.49731],
       [-53.73856],
       [-50.60245],
       ...,
       [-17.57865],
       [-17.4322 ],
       [-17.27229]]), array([[-48.68046],
       [-54.76069],
       [-51.38137],
       ...,
       [-17.49081],
       [-17.45769],
       [-17.35745]]), array([[-48.92503],
       [-56.70356],
       [-53.49392],
       ...,
       [-17.45165],
       [-17.35543],
       [-17.38622]]), array([[-48.6503 ],
       [-54.85603],
       [-51.28867],
       ...,
       [-17.48774],
       [-17.43703],
       [-17.42829]]), array([[-48.95243],
       [-54.6285 ],
       [-51.60266],
       ...,
       [-17.47794],
       [-17.48089],
       [-17.24839]]), array([[-48.4344 ],
       [-54.87377],
       [-51.80432],
       ...,
       [-17.58775],
       [-17.39783],
       [-17.34112]]), array([[-48.65129],
       [-55.08585],
       [-51.51517],
       ...,
       [-17.57968],
       [-17.40992],
       [-17.35419]]), array([[-48.63227],
       [-54.99026],
       [-51.49241],
 

In [539]:
# check if any array is not 16001 x 2...
for x in X:
    if x.shape != (16001, 1): print('This example is not the correct shape')

In [540]:
from pympler import asizeof
print (id (Y))
# Replace "0x1ceb5f50900" with the actual memory address you want to inspect
memory_address = int(((hex(id(Y)))), 16)

# Use pympler's asizeof to get the size of the object at the specified memory address
object_size = asizeof.asizeof(memory_address)

print(f"Size of object at memory address {hex(memory_address)}: {object_size} bytes")


2464260432640
Size of object at memory address 0x23dc15e2300: 32 bytes


In [567]:
# Converting the 3D array to a 2D numpy array, best way to run data into a NN
X_data = np.array(X)
X_data.shape
print(X_data.shape)
# Picks out the unique names out of the list
class_names = list(set(Y))

# Turning each file name into a specific number
labeled_classes = {class_name: label for label, class_name in enumerate(class_names)}
for k,v in labeled_classes.items():
  print (k,v)

# Takes the numbers from the last step and puts them into a numpy array
Y_data = np.array([labeled_classes[label] for label in Y])

print("IN CAPS", + labeled_classes[Y[689]])


print(Y_data[500])
with open("output.txt", "w") as f:
  print("Checking for ordinal equality...", file=f)

  for index_num in range(len(Y_data)):  # Iterate over the range of indices
    print(f'{((Y_data[index_num]))}, \t,  {labeled_classes[Y[index_num]]}',  file = f) 
    if (Y_data[index_num] !=  labeled_classes[Y[index_num]]):
      print('Order not equal', file = f)
      print('\n')
  f.close()

val_a = Y_data[0]
val_b = None
for index_num in range(len(Y_data)):
  transfer_val = val_a
  val_b = transfer_val
  val_a = Y_data[index_num]
  if (val_b != val_a):
    print("Change of index at " , index_num, '\t')

print(Y_data)
print(len(Y_data))
#Y_num = np.unique(Y_data)
Y_num = Y_data
print(Y_num)



#print (class_data[0])

"""""
output_file_path = 'output.txt'

with open(output_file_path, 'w') as file:
    for key, value in connectingXandY.items():
        file.write(f"Class {key}:\n")
        file.write(np.array2string(value, separator=', '))
        file.write("\n\n")

print(f'Data has been written to {output_file_path}')
"""""




#print(connectXandY.keys())

(1200, 16001, 1)
H2O 0
ETOH 1
Tube 2
CPW 3
SynSal 4
AML 5
Syn6Sal 6
ISO 7
PBS 8
Glucose 9
HSF 10
BSA 11
IN CAPS 10
0
Change of index at  100 	
Change of index at  200 	
Change of index at  300 	
Change of index at  400 	
Change of index at  500 	
Change of index at  600 	
Change of index at  700 	
Change of index at  800 	
Change of index at  900 	
Change of index at  1000 	
Change of index at  1100 	
[5 5 5 ... 2 2 2]
1200
[5 5 5 ... 2 2 2]


'""\noutput_file_path = \'output.txt\'\n\nwith open(output_file_path, \'w\') as file:\n    for key, value in connectingXandY.items():\n        file.write(f"Class {key}:\n")\n        file.write(np.array2string(value, separator=\', \'))\n        file.write("\n\n")\n\nprint(f\'Data has been written to {output_file_path}\')\n'

# LOAD THEN SPLIT DATA INTO PYTORCH

In [542]:
#should access data through the dictionary here? 

# select which columns to use
columns = [0]
selectedX = X_data[:, :, columns]

print("The data type of the array is " , selectedX.dtype, " and if there's unique data values:" ,  np.unique(selectedX.dtype), sep = '\t', end = "! '\t'",)
# Check if the array contains different data types
has_mixed_types = len(np.unique(selectedX.dtype)) > 1

if has_mixed_types:
    print("The array contains different data types.")
else:
    print("The array has a consistent data type.")
print(f'The shape of dataX is {selectedX.shape}')
print(f'The shape of dataY is {Y_num.shape}')
print(selectedX)
# split data into train and test sets stratified by class label
#trainX, testX, trainY, testY = train_test_split(selectedX[None, None, columns], Y_num, test_size = 0.2, random_state = 0, stratify = Y_data)

# training data histogram
#plt.hist([trainY, testY], bins = 15, label = ['Train Set', 'Test Set'])
#plt.title('Histogram of Class Labels in Data Splits')
#plt.legend()

The data type of the array is 	float64	 and if there's unique data values:	[dtype('float64')]! '	'The array has a consistent data type.
The shape of dataX is (1200, 16001, 1)
The shape of dataY is (1200,)
[[[-48.49731]
  [-53.73856]
  [-50.60245]
  ...
  [-17.57865]
  [-17.4322 ]
  [-17.27229]]

 [[-48.68046]
  [-54.76069]
  [-51.38137]
  ...
  [-17.49081]
  [-17.45769]
  [-17.35745]]

 [[-48.92503]
  [-56.70356]
  [-53.49392]
  ...
  [-17.45165]
  [-17.35543]
  [-17.38622]]

 ...

 [[-49.57227]
  [-65.6377 ]
  [-64.75055]
  ...
  [-15.94926]
  [-15.72438]
  [-15.7309 ]]

 [[-49.57227]
  [-65.6377 ]
  [-64.75055]
  ...
  [-15.94926]
  [-15.72438]
  [-15.7309 ]]

 [[-49.57227]
  [-65.6377 ]
  [-64.75055]
  ...
  [-15.94926]
  [-15.72438]
  [-15.7309 ]]]


# Make NN

In [543]:
#%%
import torch
import torchvision
from torchvision import transforms, datasets
from torch.utils.data import SubsetRandomSampler


In [544]:
#myList = ([[True, False], [False, False]], dtype = torch.bool)
tensor = torch.zeros([2, 4], dtype = torch.bool)
tensor[0][1] = True
tensor[1][2] = True
#tensor[1] = True
#tensor[1]
print(tensor)

tensor([[False,  True, False, False],
        [False, False,  True, False]])


In [545]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", device)


#convert numpy array to torch tensor
torch_selected_X = torch.from_numpy(selectedX)
torch_Y_num = torch.from_numpy(Y_num)
print("Torch y_num is: ", torch_Y_num)
print(torch_selected_X.size())
print(torch_selected_X[0][2])
xx = torch.reshape(torch_selected_X, (1200, 16001))
print(xx.size())
print(xx[100])
print(f'The shape of dataX is {torch_selected_X.shape}')
print(labeled_classes)


Using device: cuda
Torch y_num is:  tensor([5, 5, 5,  ..., 2, 2, 2], dtype=torch.int32)
torch.Size([1200, 16001, 1])
tensor([-50.6024], dtype=torch.float64)
torch.Size([1200, 16001])
tensor([-48.2867, -55.7208, -53.0941,  ..., -16.8124, -16.7583, -16.4882],
       dtype=torch.float64)
The shape of dataX is torch.Size([1200, 16001, 1])
{'H2O': 0, 'ETOH': 1, 'Tube': 2, 'CPW': 3, 'SynSal': 4, 'AML': 5, 'Syn6Sal': 6, 'ISO': 7, 'PBS': 8, 'Glucose': 9, 'HSF': 10, 'BSA': 11}


In [546]:
import subprocess as sp
import os
torch.cuda.empty_cache()
def get_gpu_memory():
    command = "nvidia-smi --query-gpu=memory.free --format=csv"
    memory_free_info = sp.check_output(command.split()).decode('ascii').split('\n')[:-1][1:]
    memory_free_values = [int(x.split()[0]) for i, x in enumerate(memory_free_info)]
    return memory_free_values

preload_gpu_memory= get_gpu_memory();

In [576]:


connectingXandY = {}
print (xx.shape[0])
for sample_num in range(xx.shape[0]):
    # Add the sample to the dictionary with the corresponding label as the key

    # Convert integer tensor to float32 first

    tensor_float64 = torch.tensor(Y_num[sample_num], dtype=torch.float64)
    #zeroth_digit_to_append = ([sample_num])
    tensor_with_digit = torch.cat((tensor_float64 , xx[sample_num, :]))


if isinstance(connectingXandY, dict):
    print("connectingXandY is a dictionary")
elif isinstance(connectingXandY, set):
    print("connectingXandY is a set")
else:
    print("connectingXandY is neither a dictionary nor a set")

print(connectingXandY.keys())

print(connectingXandY.values())






1200


RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

In [ ]:


connectingXandY = {}
for label_index in range(12):
    class_data = xx[Y_data == label_index]
    connectingXandY.update({label_index: class_data})
    #plt.plot(class_data[:,:,0].mean(axis = 0), label = class_names[label_index])

if isinstance(connectingXandY, dict):
    print("connectingXandY is a dictionary")
elif isinstance(connectingXandY, set):
    print("connectingXandY is a set")
else:
    print("connectingXandY is neither a dictionary nor a set")

print(connectingXandY.keys())

print(connectingXandY.values())






In [ ]:
#{Labels, {Sample_num, wavelength_num}}

import torch
from torch.utils.data import Dataset, DataLoader

if isinstance(connectingXandY, dict):
    print("connectingXandY is a dictionary")
elif isinstance(connectingXandY, set):
    print("connectingXandY is a set")
else:
    print("connectingXandY is neither a dictionary nor a set")

class MyDataset((Dataset)):
    def __init__(self, device, connectingXandY):
        self.device = device
        self.data = []
        self.label = []
        self.short_label = []
        self.length1 = 0
        self.conglomerate = []
        self.labels1 = 0
        self._process_data(connectingXandY, 0)
        
        # Convert lists to tensors and stack them

        #self.data = torch.stack([torch.tensor(item, dtype=torch.float32) for item in self.data])
        #self.labels = torch.tensor(self.labels, dtype=torch.int64)
        
        # Move tensors to the specified device

        #self.data = self.data.to(device)
        
        #self.labels = self.labels.to(device)
        #self.finaldict = self.finaldict.to(device)

        self.length1 = self.length1

    #label = 0
    def _process_data(self, d, parent_key=None):
        if isinstance(d, dict):
            for k, v in d.items():
                if isinstance(v, dict):
                    self._process_data(v, k)  # Recursively process nested dictionaries
                elif isinstance(v, torch.Tensor):
                    if not (self._peek_first_item(v).dtype == torch.float64):
                        parent_key = k
                        self._process_data(v, parent_key)  # Recursively process non-float64 tensors
                    elif (self._peek_first_item(v).dtype == torch.float64):
                        new_entry = torch.tensor([parent_key], dtype=v.dtype)
                        updated_tensor = torch.cat((new_entry, v))
                        d[k] = updated_tensor  # Update the dictionary with the concatenated tensor
        
        
        
        
        elif isinstance(d, torch.Tensor):
            raise ValueError("Encountered unexpected tensor outside of dictionary structure.")
        else:
            raise ValueError(f"Mismatch type found for item: {d}. Expected dictionary.")

    def _peek_first_item(self, tensor):
        iterator = iter(tensor)
        try:
            first_item = next(iterator)
            return first_item
        except StopIteration:
            raise ValueError("The iterable is empty.")


        else:
            
            raise ValueError(f"Mismatch type found for item item:  {d} != {dict} or {(torch.Tensor)}")
                   
    def __peek__first__item__(self, tensor):
        iterator = iter(tensor)
        try:
            first_item = next(iterator)
            return first_item
        except StopIteration:
            raise ValueError("The iterable is empty.")
        


    def __getitem__(self, idx):

        if idx >= len(self):
            raise IndexError(f"Index {idx} out of range")
        # Convert idx to appropriate indices
        else:
            firstDim = idx // 100
            secondDim = idx % 100
       # idy = str(idx)
        #firstDim = int(idy[0])
        #secondDim = int(idy[1] + idy[2])
        #dataset_iterator = iter(self)
# 12 * 100 ... if i = 402 --> go to [4][2] if item = 499 go to [4][99]
# Get the first item (first row) in the dataset
    #num / 12 --> 
        #first_row = next(dataset_iterator)
        data = self.data[firstDim][secondDim].to(self.device)
        #data = self.data
        
        for current_short_label in self.short_label:
            if self.label[idx] == current_short_label:
                label = torch.tensor(current_short_label, dtype=torch.int64).to(self.device)
                break
        return data, label

    def __isequal__(self, idx):
        for idx, (data, label) in enumerate(self):
            expected_data = connectingXandY[idx // 100][idx % 100]
            
    # Ensure both tensors are on the same device
            device = data.device
            expected_data = expected_data.to(device)
    
            if torch.equal(data, expected_data):
    # print(data, expected_data ) : if you want to verify loop works
                continue
            elif(): 
                continue
                expected_label = connectingXandY()[connectingXandY.values().index(16)]
            else:
                raise ValueError(f"Mismatch found at index {idx}: {data} != {expected_data}")
        return None
    
    def __len__(self):
        return self.length1
    

# Example usage:
''' connectingXandY = {
    0: [0.1, 0.2, 0.3],
    1: [0.4, 0.5, 0.6]
}
unsplitdataset = MyDataset(device, connectingXandY)

dataloader = DataLoader(unsplitdataset, batch_size=2, shuffle=True)

for data, label in dataloader:
    print(data, label)
unsplitdataset = MyDataset(device, connectingXandY)'''

#unsplitdataset = MyDataset(device, connectingXandY)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
unsplitdataset = MyDataset(device, connectingXandY)

In [ ]:
for idx, (label, data) in enumerate(unsplitdataset):
    print(f"Label:, {label}, \t, data: {data}")

In [ ]:
for idx, (data, label) in enumerate(unsplitdataset):
    expected_data = connectingXandY[idx // 100][idx % 100]
    
    # Ensure both tensors are on the same device
    device = data.device
    expected_data = expected_data.to(device)
    
    if torch.equal(data, expected_data):
        # print(data, expected_data ) : if you want to verify loop works
        continue
    else:
        raise ValueError(f"Mismatch found at index {idx}: {data} != {expected_data}")

In [ ]:

# Example usage:

print(unsplitdataset.__len__())
print(unsplitdataset.__getitem__(112))
#print("The loaded into GPU memory labels are: ", unsplitdataset.labels)
#print("The loaded into GPU memory data is: ", unsplitdataset.data)
#print(unsplitdataset.data) # <--- can access deeper in the array
#print(unsplitdataset.data[11])
#print(unsplitdataset.finaldict[1])
print(unsplitdataset.__len__())
print("The number of labels is" , f'{len(unsplitdataset.label)}')
#print(unsplitdataset.__len__())
trainset1, testset1 = torch.utils.data.random_split(unsplitdataset, (0.2, 0.8))
print(len(trainset1))
print(len(testset1)) 

#print("Is the dataloader on the the GPU:", trainset1[0][1].is_cuda)


trainset_loader = torch.utils.data.DataLoader(trainset1, batch_size = 240, shuffle= False )
testset_loader = torch.utils.data.DataLoader(testset1, batch_size = 60, shuffle= False )

'''train_features, train_labels = next(iter(trainset_loader))
print(f"Feature batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")
img = train_features[0].squeeze()
label = train_labels[0]
plt.imshow(img, cmap="gray")
plt.show()
print(f"Label: {label}")'''

#for inputs, labels in trainset_loader:
   # inputs, labels = inputs.to(device), labels.to(device)
#(labels, {number of data points, amplitude)})
#print("Is the dataloader on the the GPU:", trainset_loader[0][1].is_cuda)
#print(connectingXandY[0])

#print(unsplitdataset.data[1])
#print(trainset1.data[1])
# Use DataLoader to load data into GPU memory
#trainset1_loader = DataLoader(unsplitdataset, batch_size=5, shuffle=True, )
#pin_memory = True
#print('checking if dataset is loaded into gpu memory :' ,  unsplitdataset.device)
# Verify that the data is loaded correctly
#for data, label in trainset_loader:
    #print("Data:", data)
    #print("Label:", label)

postload_gpu_memory = get_gpu_memory()
print(postload_gpu_memory)
#print(f'{preload_gpu_memory}');
#print(f'{postload_gpu_memory}');
#for channel in postload_gpu_memory:
    #preload_gpu_memory[channel]-postload_gpu_memory[channel]



In [ ]:
train_features, train_labels= next(iter(trainset_loader))

print(f"Features batch shape: {train_features.size()}")
print(f"Labels batch shape: {train_labels.size()}")

In [ ]:
for data, labels in trainset_loader:
        inputs = data.float()
        print(labels)

In [ ]:

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
    #Input Layer --> hidden layer (certain # of neurons) --> output (15 classes)
    #in_features - what we are putting into the model, i made the assumption that it is the 2 logmag values, in the tutorial, 
    #hes doing flowers and his in features are 4 diff characterists of flowers


#was 16001, h1 = 200, h2 = 200, out = 12
    def __init__(self, in_features= 16001, h1= 100, h2=100, out_features=12): #3 sets of features? 2 x 15 x frequency? #the h1, h2 are just hidden layers, the output features are just the 0-14, and the input is just whatever we decide we need to be the input
        super().__init__() 
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(in_features, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, out_features)
    
    def forward(self, x):
        x = self.flatten(x)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        return x
#didnt normalize featuers
#unsure if linear only layer is correct
#

In [ ]:
torch.manual_seed(5)
model = Model().to(device)
model.train()

In [ ]:
# Define optimizer and loss function
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()
# Training loop
# Training loop
EPOCHS = 3
for epoch in range(EPOCHS):
    for data, labels in trainset_loader:
        inputs = data.float()
        outputs = model(inputs)
        print(outputs)
        # Take the last output from the sequence
        #if outputs.size(1) > 0:  # Check if the sequence length is greater than 0
            #outputs = outputs[:, -1, :]
        #else:
           # print("Found an empty sequence in the batch.")
           # continue

        targets = labels  # Use the correct variable for your targets

        print(outputs.shape)  # Should print torch.Size([5, 12])
        print(labels)
        loss = criterion(outputs, targets)
        
        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        
        
    
    print(f'Epoch [{epoch+1}/{EPOCHS}], Loss: {loss.item():.4f}')
    '''The reduction in the number of labels from 5 to 2 when going from self.fc2 to self.out is likely due to the way you’re handling your data in the forward pass of your model.

In your code, you’re taking the last output from the sequence with outputs = outputs[:, -1, :]. This means that for each input sequence, you’re only considering the last output for calculating the loss. If your input data has variable sequence lengths, this could result in a mismatch between the batch size of your outputs and targets.

Also, in your training loop, you’re setting targets = labels, but labels is not defined in the loop. I think you meant to use fakelabels instead of labels.

Here’s a corrected version of your training loop:'''

In [ ]:
# Assuming you have a DataLoader for your test set: testset_loader

model.eval()  # Set the model to evaluation mode

with torch.no_grad():  # No need to track the gradients
    correct = 0
    total = 0
    i = 0
    for data, labels in testset_loader:
        print(i)
        #inputs = torch.tensor(data, dtype=torch.float64)
        print(inputs)
        inputs = data.float()
        outputs = model(inputs)
        i += 1
       

        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy of the network on the test data: {100 * correct / total}%')

# AUXILLARY/BACK-UP CODE

In [ ]:
import matplotlib.pyplot as plt
index = 1

In [ ]:
plt.imshow(X[1])

In [ ]:
idx = 504
idy = str(idx)
firstDim = idy[0]
secondDim = idy[1] + idy[2]
print ("is our answer: " , firstDim + secondDim, "an instance of string: ", f'{isinstance(firstDim + secondDim, str)}')
print ()

In [ ]:
#{Labels, {Sample_num, wavelength_num}}

import torch
from torch.utils.data import Dataset, DataLoader

if isinstance(connectingXandY, dict):
    print("connectingXandY is a dictionary")
elif isinstance(connectingXandY, set):
    print("connectingXandY is a set")
else:
    print("connectingXandY is neither a dictionary nor a set")

class MyDataset((Dataset)):
    def __init__(self, device, connectingXandY):
        self.device = device
        self.data = []
        self.label = []
        self.short_label = []
        self.length1 = 0
        self._process_data(connectingXandY)
        
        # Convert lists to tensors and stack them

        #self.data = torch.stack([torch.tensor(item, dtype=torch.float32) for item in self.data])
        #self.labels = torch.tensor(self.labels, dtype=torch.int64)
        
        # Move tensors to the specified device

        #self.data = self.data.to(device)
        
        #self.labels = self.labels.to(device)
        #self.finaldict = self.finaldict.to(device)

        self.length1 = self.length1

    def _process_data(self, d):
        if isinstance(d, dict):
            for k, v in d.items():
                if isinstance(v, dict):
                    self._process_data(v)
                else:
                    self.data.append(v)  # Assuming v is a list of numerical values
                    self.short_label.append(k)
                    for i in range(len(v)):
                        self.label.append(k)  # Assuming k is an integer label
                        self.length1 += 1
                    #self.finaldict.update({v:k}) #Make reverse dict so we can have data --> labels, and labels --> data
                    #self.length1 += len(v)
        elif isinstance(d, set):
            for item in d:
                self.data.append(item)  # Assuming item is a list of numerical values
                #self.labels.append(-1)  # Placeholder for labels
                
    def __len__(self):
        return self.length1
#{label,{sameples, wavelengths}}
    def __getitem__(self, idx):

        if idx >= len(self):
            raise IndexError(f"Index {idx} out of range")
        # Convert idx to appropriate indices
        else:
            firstDim = idx // 100
            secondDim = idx % 100
       # idy = str(idx)
        #firstDim = int(idy[0])
        #secondDim = int(idy[1] + idy[2])
        #dataset_iterator = iter(self)
# 12 * 100 ... if i = 402 --> go to [4][2] if item = 499 go to [4][99]
# Get the first item (first row) in the dataset
    #num / 12 --> 
        #first_row = next(dataset_iterator)
        data = self.data[firstDim][secondDim].to(self.device)
        #data = self.data
        
        for current_short_label in self.short_label:
            if self.label[idx] == current_short_label:
                label = torch.tensor(current_short_label, dtype=torch.int64).to(self.device)
                break
        return data, label

    def __isequal__(self, idx):
        for idx, (data, label) in enumerate(self):
            expected_data = connectingXandY[idx // 100][idx % 100]
    
    # Ensure both tensors are on the same device
            device = data.device
            expected_data = expected_data.to(device)
    
            if torch.equal(data, expected_data):
    # print(data, expected_data ) : if you want to verify loop works
                continue
            if torch.equal(label, )
            else:
                raise ValueError(f"Mismatch found at index {idx}: {data} != {expected_data}")
        return None
    

   
# Example usage:
''' connectingXandY = {
    0: [0.1, 0.2, 0.3],
    1: [0.4, 0.5, 0.6]
}
unsplitdataset = MyDataset(device, connectingXandY)

dataloader = DataLoader(unsplitdataset, batch_size=2, shuffle=True)

for data, label in dataloader:
    print(data, label)
unsplitdataset = MyDataset(device, connectingXandY)'''

#unsplitdataset = MyDataset(device, connectingXandY)


   

In [ ]:
idx = 101
firstDim = idx // 100
secondDim = idx % 100
print (firstDim, secondDim)

In [ ]:

'''
idx = 100
idy = str(idx)
firstDim = (idy[0])
secondDim = (idy[1] + idy[2])
output = int(firstDim + )
'''

In [ ]:
'''connectingXandY[1][0]

200 --> class 2 item 0

[class_][item_] ... item_num

where [item_] must handle 2 digits e.g. [0] or [20] but not [02]

so I get number: 99 --> maps to [0][99]

if number 199 --> maps to [1][99]'''

In [ ]:
connectingXandY[1][91]


In [ ]:
print(unsplitdataset.__getitem__(191))
print(unsplitdataset.length1)

print (unsplitdataset[55])

In [ ]:

for idx in range(unsplitdataset.length1):
    data, label = unsplitdataset[idx]  # Access and unpack the tuple
    expected_data = connectingXandY[idx // 100][idx % 100]

    # Ensure both tensors are on the same device
    device = data.device
    expected_data = expected_data.to(device)

    if torch.equal(data, expected_data):
        continue
    else:
        raise ValueError(f"Mismatch found at index {idx}: {data} != {expected_data}")


In [ ]:
for idx, (data, label) in enumerate(unsplitdataset):
    expected_data = connectingXandY[idx // 100][idx % 100]
    
    # Ensure both tensors are on the same device
    device = data.device
    expected_data = expected_data.to(device)
    
    if torch.equal(data, expected_data):
        # print(data, expected_data ) : if you want to verify loop works
        continue
    else:
        raise ValueError(f"Mismatch found at index {idx}: {data} != {expected_data}")
    

    # Suppose unsplitdataset is a list of tuples (data, label)
#unsplitdataset = [
   # (torch.tensor([1, 2, 3]), 0),
    #(torch.tensor([4, 5, 6]), 1),
    #(torch.tensor([7, 8, 9]), 2),
#]

#for idx, (data, label) in enumerate(unsplitdataset):
    #print(f"Index: {idx}, Data: {data}, Label: {label}")


In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(16001 * 1, 200),
            nn.ReLU(),
            nn.Linear(200, 200),
            nn.ReLU(),
            nn.Linear(200, 12),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


In [ ]:
model = NeuralNetwork().to(device)
print(model)

In [ ]:

learning_rate = 1e-3
batch_size = 240
epochs = 5

# Initialize the loss function
loss_fn = nn.CrossEntropyLoss()

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)



def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    # Set the model to training mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X.float())
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * batch_size + len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    # Set the model to evaluation mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    # Evaluating the model with torch.no_grad() ensures that no gradients are computed during test mode
    # also serves to reduce unnecessary gradient computations and memory usage for tensors with requires_grad=True
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X.float())
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")


In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

epochs = 10
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(trainset_loader, model, loss_fn, optimizer)
    test_loop(testset_loader, model, loss_fn)
print("Done!")

In [ ]:
#{Labels, {Sample_num, wavelength_num}}

import torch
from torch.utils.data import Dataset, DataLoader

if isinstance(connectingXandY, dict):
    print("connectingXandY is a dictionary")
elif isinstance(connectingXandY, set):
    print("connectingXandY is a set")
else:
    print("connectingXandY is neither a dictionary nor a set")

class MyDataset((Dataset)):
    def __init__(self, device, connectingXandY):
        self.device = device
        self.data = []
        self.label = []
        self.short_label = []
        self.length1 = 0
        self.conglomerate = []
        self.labels1 = 0
        self._process_data(connectingXandY, 0)
        
        # Convert lists to tensors and stack them

        #self.data = torch.stack([torch.tensor(item, dtype=torch.float32) for item in self.data])
        #self.labels = torch.tensor(self.labels, dtype=torch.int64)
        
        # Move tensors to the specified device

        #self.data = self.data.to(device)
        
        #self.labels = self.labels.to(device)
        #self.finaldict = self.finaldict.to(device)

        self.length1 = self.length1

    #label = 0
    def _process_data(self, d, parent_key=None):
        if isinstance(d, dict):
            for k, v in d.items():
                if isinstance(v, dict):
                    self._process_data(v, k)  # Recursively process nested dictionaries
                elif isinstance(v, torch.Tensor):
                    if not (self._peek_first_item(v).dtype == torch.float64):
                        parent_key = k
                        self._process_data(v, parent_key)  # Recursively process non-float64 tensors
                    elif (self._peek_first_item(v).dtype == torch.float64):
                        new_entry = torch.tensor([parent_key], dtype=v.dtype)
                        updated_tensor = torch.cat((new_entry, v))
                        d[k] = updated_tensor  # Update the dictionary with the concatenated tensor
        
        
        
        
        elif isinstance(d, torch.Tensor):
            raise ValueError("Encountered unexpected tensor outside of dictionary structure.")
        else:
            raise ValueError(f"Mismatch type found for item: {d}. Expected dictionary.")

    def _peek_first_item(self, tensor):
        iterator = iter(tensor)
        try:
            first_item = next(iterator)
            return first_item
        except StopIteration:
            raise ValueError("The iterable is empty.")


        else:
            
            raise ValueError(f"Mismatch type found for item item:  {d} != {dict} or {(torch.Tensor)}")
                   
    def __peek__first__item__(self, tensor):
        iterator = iter(tensor)
        try:
            first_item = next(iterator)
            return first_item
        except StopIteration:
            raise ValueError("The iterable is empty.")
        


    def __getitem__(self, idx):

        if idx >= len(self):
            raise IndexError(f"Index {idx} out of range")
        # Convert idx to appropriate indices
        else:
            firstDim = idx // 100
            secondDim = idx % 100
       # idy = str(idx)
        #firstDim = int(idy[0])
        #secondDim = int(idy[1] + idy[2])
        #dataset_iterator = iter(self)
# 12 * 100 ... if i = 402 --> go to [4][2] if item = 499 go to [4][99]
# Get the first item (first row) in the dataset
    #num / 12 --> 
        #first_row = next(dataset_iterator)
        data = self.data[firstDim][secondDim].to(self.device)
        #data = self.data
        
        for current_short_label in self.short_label:
            if self.label[idx] == current_short_label:
                label = torch.tensor(current_short_label, dtype=torch.int64).to(self.device)
                break
        return data, label

    def __isequal__(self, idx):
        for idx, (data, label) in enumerate(self):
            expected_data = connectingXandY[idx // 100][idx % 100]
    
    # Ensure both tensors are on the same device
            device = data.device
            expected_data = expected_data.to(device)
    
            if torch.equal(data, expected_data):
    # print(data, expected_data ) : if you want to verify loop works
                continue
            else:
                raise ValueError(f"Mismatch found at index {idx}: {data} != {expected_data}")
        return None
    
    def __len__(self):
        return self.length1
    

# Example usage:
''' connectingXandY = {
    0: [0.1, 0.2, 0.3],
    1: [0.4, 0.5, 0.6]
}
unsplitdataset = MyDataset(device, connectingXandY)

dataloader = DataLoader(unsplitdataset, batch_size=2, shuffle=True)

for data, label in dataloader:
    print(data, label)
unsplitdataset = MyDataset(device, connectingXandY)'''

#unsplitdataset = MyDataset(device, connectingXandY)